# Generated by Django 4.2.11 on 2026-05-03 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('p', models.FloatField()),
                ('f', models.FloatField()),
                ('steps_count', models.IntegerField(default=0)),
                ('grid_data', models.JSONField()),
                ('fire_histogram', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
